---
created: '2021-03-08T16:39:06.053561Z'
creator: sentry
source: tests/sentry/grouping/test_variants.py
---
system:
  hash: "e0b4eea234ff891472cb927c00153bbe"
  component:
    system*
      exception*
        stacktrace*
          frame*
            function*
              "_main"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start_internal"
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start::{{closure}}"
          frame* (marked in-app by stack trace rule (function:log_demo::* +app))
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
system-depth-1:
  hash: "6bcfd06e9f2d4ecc13c3068c56f08a3d"
  component:
    system-depth-1*
      exception*
        stacktrace*
          frame*
            function*
              "log::__private_api_log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
system-depth-2:
  hash: "530d3e1d0e491b1429075d946b93c5cd"
  component:
    system-depth-2*
      exception*
        stacktrace*
          frame* (marked in-app by stack trace rule (function:log_demo::* +app))
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
system-depth-3:
  hash: "00cf41c4907b1c15c20189007fd0cffd"
  component:
    system-depth-3*
      exception*
        stacktrace*
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start::{{closure}}"
          frame* (marked in-app by stack trace rule (function:log_demo::* +app))
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
system-depth-4:
  hash: "804fe59ad967ff79f51148c2fc1e1c2c"
  component:
    system-depth-4*
      exception*
        stacktrace*
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start::{{closure}}"
          frame* (marked in-app by stack trace rule (function:log_demo::* +app))
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
system-depth-5:
  hash: "7c63b39cc8c54948f95871205ac3aeb5"
  component:
    system-depth-5*
      exception*
        stacktrace*
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start::{{closure}}"
          frame* (marked in-app by stack trace rule (function:log_demo::* +app))
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
system-depth-max:
  hash: "e0b4eea234ff891472cb927c00153bbe"
  tree_label: "_main"
  component:
    system-depth-max*
      exception*
        stacktrace*
          frame*
            function*
              "_main"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start_internal"
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start::{{closure}}"
          frame* (marked in-app by stack trace rule (function:log_demo::* +app))
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
