---
created: '2021-02-15T18:20:09.714812Z'
creator: sentry
source: tests/sentry/grouping/test_variants.py
---
app-depth-1:
  hash: "eb87c1031dba55b67df86fb9fff59dc6"
  component:
    app-depth-1*
      exception*
        stacktrace* (discarded because stack trace only contains 1 frame which is under the configured threshold by stack trace rule (family:native min-frames=2))
          frame* (marked in-app by stack trace rule (function:log_demo::* +app))
            function*
              "log_demo::main"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
app-depth-max:
  hash: null
  component:
    app-depth-max (exception of app-depth-1/system takes precedence)
      exception (ignored because this variant does not have a contributing stacktrace, but others do)
        stacktrace (discarded because stack trace only contains 1 frame which is under the configured threshold by stack trace rule (family:native min-frames=2))
          frame (non app frame)
            function*
              "_main"
          frame (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start_internal"
          frame (non app frame)
            function*
              "___rust_maybe_catch_panic"
          frame (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
          frame (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start::{{closure}}"
          frame* (marked in-app by stack trace rule (function:log_demo::* +app))
            function*
              "log_demo::main"
          frame (non app frame)
            function*
              "log::__private_api_log"
        type*
          "log_demo"
        value*
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
system:
  hash: "e0b4eea234ff891472cb927c00153bbe"
  component:
    system*
      exception*
        stacktrace*
          frame*
            function*
              "_main"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start_internal"
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start::{{closure}}"
          frame* (marked in-app by stack trace rule (function:log_demo::* +app))
            function*
              "log_demo::main"
          frame*
            function*
              "log::__private_api_log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
